/* Live CUSB listings available from the Others column of the About menu. */
(function () {
  const resources = {
    tenders: ['Tenders', 'Procurement opportunities and tender notices published by CUSB.', 'tenders.html'],
    notices: ['Notices', 'Official notices published by the University.', 'news-events.html?type=notice'],
    'upcoming-events': ['Upcoming Events', 'Forthcoming University events and announcements.', 'news-events.html?type=event'],
    'archived-events': ['Archived Events', 'Past events and their official records.', 'news-events.html#archived'],
    'photo-gallery': ['Photo Gallery', 'University photo gallery, including convocation photographs.', 'index.html#gallery'],
    recruitment: ['Recruitment', 'Recruitment announcements and related notifications.', 'careers.html'],
    download: ['Download', 'University downloads, forms and documents.', 'downloads.html'],
    'recent-event': ['Recent Event', 'Latest event reports and University news.', 'news-events.html#recent'],
    'academic-highlights': ['Academic Highlights', 'Academic news, achievements and highlights.', 'news-events.html#academic-highlights'],
    circulars: ['Circular / Notification / Office Order', 'Circulars, notifications and office orders.', 'news-events.html?type=circular'],
    'foundation-day': ['Foundation Day', 'Foundation Day information and event material.', 'news-events.html?type=event']
  };
  const records = {
    tenders: ['Supply of Laboratory Chemicals and Consumables Items (CUSB/PSD/Chemicals and Consumables/LTE/08/2026-27) — Last Date: 21 August 2026', 'Tender for Construction of Firing Range in CUSB (CUSB/PSD/EE/T/07/2026-27) — Last Date: 21 August 2026', 'Limited Tender Enquiry for Chain-link fencing behind the Classroom Building for facilitating KVS at CUSB — Last Date: 16 June 2026', 'Tender Bid Document for Construction of Approach Road along the Boundary Wall towards Village Karhara for patrolling and security — Last Date: 10 June 2026', 'Tender Bid Document for Aluminium Partition work for faculty chambers at Swaminathan Bhawan — Last Date: 19 June 2026', 'Construction of Visitor Shed at V.D.S. Boys’ Hostel — Last Date: 19 June 2026', 'Construction of Toilet Block near Type III and IV Residential Building — Last Date: 04 June 2026', 'Covering of Open Drainage Channel from Animal Husbandry Unit to Dhanvantri Arogya Vatika — Last Date: 29 April 2026'],
    notices: ['Hostel allotment list for UG 1st Semester of Boys and Girls Hostels – 2024', 'Election Commission of India regarding vacancies in Academic Discipline'],
    'upcoming-events': ['Preparatory Workshop on Creating Bhartiya Bhasha Ecosystem — 07–08 August 2026', 'National Seminar on Integration of AI in Physical Education and Sports Sciences — 08–09 October 2026', 'Drawing Competition under NSS Swachhta Pakhwada Programme — 05 August 2026', '24 Days Faculty Induction Programme (GURU DAKSHTA) — 04, 10 and 14 June 2026', 'Observation of World No Tobacco Day 2026 and No Tobacco Pledge Ceremony — 31 May 2026', 'NEP 2020 Orientation and Sensitization Programme — 26 May–04 June 2026', 'Interns Talk — 21 May 2026', 'How to Navigate the New Emerald Insight Platform — 27 April 2026', '1st Vice-Chancellor’s Cup: CUSB Box Cricket League — 20 April 2026', 'Result of 1st round University Website Redesign & Optimization Challenge'],
    'archived-events': ['Workshop on NPS and UPS for CUSB Employees — 14 February 2026', 'Two-Day National Conference on “Bharatiya Bhasha Pariwar: A Shared Heritage” — 19–20 January 2026', 'National Workshop on “Advocacy & Client Counseling in the 21st Century” — 09 January 2026', 'Deeksharambha orientation programme for newly enrolled BBA LLB students — 28 October 2024', 'Prof. Shekhar C. Mande lecture on India’s Journey in Science Through Centuries — 24 October 2024', 'Swachhta Hi Seva Pakhwada — 17 September–02 October 2024', 'Awareness campaign and tree plantation by the Department of Agriculture — 18 September 2024', 'Blood Donation Camp by the National Service Scheme Unit — 13 September 2024'],
    recruitment: ['Junior Research Fellow (01 post) under IITM Pune-funded Project CUSB-RP-110, Department of Environmental Science — 29 July 2026', 'Project Associate (01 post) under ANRF-funded Project CUSB-RP-127, Department of Geology — 08 July 2026', 'Project Assistant (01 post) under ANRF-funded Project CUSB-RP-129, Department of Chemistry — 07 July 2026', 'Junior Research Fellow (01 post) under ANRF-funded Project CUSB-RP-128, Department of Geology — 07 July 2026', 'Junior Research Fellow (01 post) under ANRF-funded Project CUSB-RP-130, Department of Agriculture — 06 July 2026', 'Project Associate (01 post) and MTS (01 post) under PM Professorship — 18 June 2026', 'Appointment of Vice-Chancellor of Central University of South Bihar — 22 May 2026', 'CRS Project Fellow (Junior) posts under UGC-DAE-CSR-funded projects CUSB-RP-124 and CUSB-RP-123'],
    'recent-event': ['MoU signed between CUSB and Hindustan Copper Limited to strengthen industry-academia collaboration', '12th International Yoga Day celebration at CUSB', 'Workshop on One District One Crop: Doubling Farmers’ Income for Sustainable Livelihood in Gaya District', 'Seminar on World Environment Day organised by the Department of Environmental Sciences', 'Plantation of 620 saplings at CUSB campus on World Environment Day', 'Panel discussion on the three-language formula of CBSE', 'Panel discussion on Prime Minister Modi’s 7 Point Appeal', 'Webinar on Regulatory Affairs by the Department of Pharmacy', 'Community feast, Krishi Shramyogi – Samrasata Sahabhoj', 'AVINYA 3.0 cross-continental conference organised by SLG and IIC'],
    'academic-highlights': ['Rs. 64 lakh ANRF grant to Dr. Saptarshi Ghosh for research on nucleic acid structures', 'Geography research scholar Adriza Dutta presented a paper at an international conference in China', 'Four Mass Communication and Media students placed at Prabhat Khabar', 'Dr. Chandana Suba attended the Janjatiya Garima Utsav at Rashtrapati Bhawan', 'Nineteen CUSB students received placements with Azim Premji Foundation', 'Research article of Dr. Mayank Yuvaraj included among WILEY’s top 10% most-viewed papers', 'Dr. Rohit Ranjan Shahi received a Rs. 41 lakh BARC grant on magnetic properties of alloys', 'Eight Sociological Studies students placed with Kshamtalaya Foundation', 'Two-day geological field excursion for UG–PG Geology students'],
    circulars: ['Public Self Disclosure', 'Safety and Security Advisory during Convocation', 'Selection trial notice for the CUSB Kho-Kho (Women) team for East Zone Inter-University Tournament 2024–25', 'Office Order No. 14/2025 dated 30 January 2025'],
    download: ['Students-related downloads', 'Reservation Roster', 'GH and RH 2026 and GH and RH 2025', 'Notification for Vehicle Stickers and Transport Related Notice', 'Vehicle Requisition Format', 'Leave circular, English and Hindi leave applications, duty leave and joining report', 'LTC Application and Bill Settlement Forms', 'T.A./D.A. reimbursement claim form and Annual Property Return', 'Identity Card Application and duplicate identity-card notification', 'Project-related proformas, proposals and closure report', 'Career Advancement Scheme (CAS) notices, annexures and PBAS proformas', 'Teaching and Non-Teaching Reservation Registers / Rosters', 'General Financial Rules 2017 and Supplier Registration Form', 'Medical reimbursement, empanelled-hospital, health-scheme and referral-slip forms', 'Swami Vivekanand Lecture Hall booking SOP and format', 'Nomination and Children Education Allowance forms'],
    'foundation-day': ['Foundation Day — 27 February 2026', 'Constitution of Committee for Foundation Day'],
    'photo-gallery': ['The official gallery includes CUSB event and convocation photographs. The replica gallery is available through the Campus Photo Gallery section.']
  };
  const galleryAssets = [
    ['A1', '6f7be9fec188c10a.jpg'], ['A4', '870dcf2e4146aa93.jpg'], ['A2', '32b8482612fde8c3.jpg'], ['A3', '4ae6cc6e9072fd09.jpg'],
    ['A5', '286793f9360de714.jpg'], ['A6', '607b7729312cbbef.jpg'], ['A7', '24357b16cebc8df6.jpg'], ['A8', 'a265058e2d45dba6.jpg']
  ];
  if (document.body.dataset.otherPage === 'photo-gallery') {
    document.title = 'Photo Gallery — CUSB';
    const root = document.getElementById('otherPageContent');
    if (!root) return;
    root.innerHTML = `<section class="gallery-page"><div class="container"><header class="gallery-hero"><div><span class="section-tag">Campus Photo Gallery</span><h1>Moments that define <em>our campus</em></h1><p>Explore the official event photographs preserved in the University gallery, beginning with the 3rd Convocation Ceremony collection.</p><div class="gallery-event-pill"><span class="gallery-event-dot"></span> 3rd Convocation Ceremony <strong>8 photographs</strong></div></div><div class="gallery-hero-mark"><span>03</span><small>CONVOCATION<br>COLLECTION</small></div></header><section class="gallery-toolbar" aria-label="Gallery filters"><div><span class="gallery-toolbar-label">Collection</span><button class="gallery-filter is-active" type="button" data-gallery-filter="all">All photographs</button><button class="gallery-filter" type="button" data-gallery-filter="convocation">3rd Convocation</button></div><p><strong>${galleryAssets.length}</strong> curated images</p></section><section class="gallery-event-section" data-gallery-group="convocation"><div class="gallery-section-heading"><div><span class="section-tag">Event collection</span><h2>3rd Convocation Ceremony</h2></div><p>Official gallery sequence</p></div><div class="gallery-grid">${galleryAssets.map(([label, file], index) => `<button class="gallery-card${index === 0 ? ' gallery-card-featured' : ''}" type="button" data-gallery-open="${index}" aria-label="Open photograph ${label}"><img src="assets/gallery/convocation/${file}" alt="3rd Convocation photograph ${label}" loading="${index < 3 ? 'eager' : 'lazy'}"><span class="gallery-card-shade"></span><span class="gallery-card-caption"><small>Photograph ${label}</small><b>View image <i>↗</i></b></span></button>`).join('')}</div></section><section class="gallery-note"><div class="gallery-note-icon">✦</div><div><h2>A record of University life</h2><p>This collection preserves the atmosphere, people and ceremonial moments of the University’s convocation programme in a visual sequence.</p></div></section></div></section><div class="gallery-lightbox" id="galleryLightbox" aria-hidden="true"><button class="gallery-lightbox-close" type="button" aria-label="Close image viewer">×</button><button class="gallery-lightbox-prev" type="button" aria-label="Previous image">‹</button><figure><img id="galleryLightboxImage" src="" alt=""><figcaption id="galleryLightboxCaption"></figcaption></figure><button class="gallery-lightbox-next" type="button" aria-label="Next image">›</button></div>`;
    const lightbox = document.getElementById('galleryLightbox');
    const lightboxImage = document.getElementById('galleryLightboxImage');
    const lightboxCaption = document.getElementById('galleryLightboxCaption');
    let activeIndex = 0;
    const showImage = index => { activeIndex = (index + galleryAssets.length) % galleryAssets.length; const item = galleryAssets[activeIndex]; lightboxImage.src = `assets/gallery/convocation/${item[1]}`; lightboxImage.alt = `3rd Convocation photograph ${item[0]}`; lightboxCaption.textContent = `Photograph ${item[0]} · 3rd Convocation Ceremony`; lightbox.classList.add('is-open'); lightbox.setAttribute('aria-hidden', 'false'); document.body.classList.add('gallery-lightbox-open'); };
    const closeImage = () => { lightbox.classList.remove('is-open'); lightbox.setAttribute('aria-hidden', 'true'); document.body.classList.remove('gallery-lightbox-open'); };
    root.querySelectorAll('[data-gallery-open]').forEach(card => card.addEventListener('click', () => showImage(Number(card.dataset.galleryOpen))));
    lightbox.querySelector('.gallery-lightbox-close').addEventListener('click', closeImage);
    lightbox.querySelector('.gallery-lightbox-prev').addEventListener('click', () => showImage(activeIndex - 1));
    lightbox.querySelector('.gallery-lightbox-next').addEventListener('click', () => showImage(activeIndex + 1));
    lightbox.addEventListener('click', event => { if (event.target === lightbox) closeImage(); });
    document.addEventListener('keydown', event => { if (!lightbox.classList.contains('is-open')) return; if (event.key === 'Escape') closeImage(); if (event.key === 'ArrowLeft') showImage(activeIndex - 1); if (event.key === 'ArrowRight') showImage(activeIndex + 1); });
    root.querySelectorAll('.gallery-filter').forEach(filter => filter.addEventListener('click', () => { root.querySelectorAll('.gallery-filter').forEach(item => item.classList.remove('is-active')); filter.classList.add('is-active'); }));
    return;
  }
  const entry = resources[document.body.dataset.otherPage];
  if (!entry) return;
  const [title, description, localUrl] = entry;
  const items = records[document.body.dataset.otherPage] || [];
  document.title = `${title} — CUSB`;
  document.getElementById('otherPageContent').innerHTML = `
    <section class="section"><div class="container information-panel about-detail-content"><span class="section-tag">Others</span><h1 class="section-title information-title" style="text-align:left; margin-bottom:15px;">${title}</h1><p>${description}</p>${items.length ? `<div class="feature-list-grid">${items.map(item => `<article><h3>${item}</h3><p>University record</p></article>`).join('')}</div>` : ''}<div class="official-document-links"><a href="${localUrl}">Browse ${title} <span>View →</span></a></div></div></section>`;
})();
