/**
 * Central University of South Bihar — Official Recruitment Portal Data
 * Verbatim transcription of official recruitment advertisements from University records.
 */
window.CUSB_RECRUITMENT_DATA = [
  // ─── PAGE 1 (10 Advertisements) ───
  {
    id: 1,
    page: 1,
    title: "Advertisement for the post of Junior Research Fellow (JRF) (01-Post) under IITM Pune-funded Project CUSB-RP-110 sanctioned to Prof. Pradhan Parth Sarthi, Professor, Department of Environmental Science, CUSB",
    publishedDate: "29 July 2026",
    publishedDateIso: "2026-07-29",
    closingDate: "18 August 2026",
    projectCode: "CUSB-RP-110",
    fundingAgency: "IITM Pune",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Environmental Science",
    principalInvestigator: "Prof. Pradhan Parth Sarthi, Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "M.Sc. in Environmental Science / Atmospheric Science / Meteorology / Physics / Climate Studies with minimum 55% marks and valid NET / GATE qualification.",
    fellowship: "₹37,000/- per month + HRA as per MoES / IITM guidelines."
  },
  {
    id: 2,
    page: 1,
    title: "Advertisement for the post of Project Associate (01-Post) under ANRF-funded Project CUSB-RP-127 sanctioned to Dr. Milan Kumar Sharma, Associate Professor, Department of Geology, CUSB",
    publishedDate: "08 July 2026",
    publishedDateIso: "2026-07-08",
    closingDate: "28 July 2026",
    projectCode: "CUSB-RP-127",
    fundingAgency: "ANRF",
    postName: "Project Associate",
    vacancies: 1,
    department: "Department of Geology",
    principalInvestigator: "Dr. Milan Kumar Sharma, Associate Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "M.Sc. / M.Tech in Geology / Applied Geology / Earth Sciences with minimum 55% marks.",
    fellowship: "₹31,000/- per month + HRA (with NET/GATE) or ₹25,000/- + HRA per ANRF rules."
  },
  {
    id: 3,
    page: 1,
    title: "Advertisement for the post of Project Assistant (01-Post) under ANRF-funded Project CUSB-RP-129 sanctioned to Dr. Saptarshi Gosh, Assistant Professor, Department of Chemistry",
    publishedDate: "07 July 2026",
    publishedDateIso: "2026-07-07",
    closingDate: "27 July 2026",
    projectCode: "CUSB-RP-129",
    fundingAgency: "ANRF",
    postName: "Project Assistant",
    vacancies: 1,
    department: "Department of Chemistry",
    principalInvestigator: "Dr. Saptarshi Gosh, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "B.Sc. / M.Sc. in Chemistry / Chemical Sciences with first class honors.",
    fellowship: "₹20,000/- per month + HRA as per ANRF norms."
  },
  {
    id: 4,
    page: 1,
    title: "Advertisement for the post of JRF (01-Post) under ANRF-funded Project CUSB-RP-128 sanctioned to Dr. Priti Rai, Assistant Professor, Department of Geology, CUSB",
    publishedDate: "07 July 2026",
    publishedDateIso: "2026-07-07",
    closingDate: "27 July 2026",
    projectCode: "CUSB-RP-128",
    fundingAgency: "ANRF",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Geology",
    principalInvestigator: "Dr. Priti Rai, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "M.Sc. in Geology / Hydrogeology / Remote Sensing & GIS with CSIR-UGC NET or GATE.",
    fellowship: "₹37,000/- per month + HRA."
  },
  {
    id: 5,
    page: 1,
    title: "Advertisement for the post of JRF (01-Post) under ANRF-funded Project CUSB-RP-130 sanctioned to Dr. Pranav Tripathi, Assistant Professor, Department of Agriculture, CUS",
    publishedDate: "06 July 2026",
    publishedDateIso: "2026-07-06",
    closingDate: "26 July 2026",
    projectCode: "CUSB-RP-130",
    fundingAgency: "ANRF",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Agriculture",
    principalInvestigator: "Dr. Pranav Tripathi, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "M.Sc. (Agri) in Agronomy / Soil Science / Genetics & Plant Breeding with ICAR-NET / CSIR-NET.",
    fellowship: "₹37,000/- per month + HRA."
  },
  {
    id: 6,
    page: 1,
    title: "Advertisement for the post of Project Associate (01-Post) & MTS (01-Post) under PM Professorship, CUSB",
    publishedDate: "18 June 2026",
    publishedDateIso: "2026-06-18",
    closingDate: "08 July 2026",
    projectCode: "PM-PROF-01",
    fundingAgency: "PM Professorship Chair",
    postName: "Project Associate & Multi-Tasking Staff (MTS)",
    vacancies: 2,
    department: "Office of the PM Professorship Chair",
    principalInvestigator: "Coordinator, PM Professorship Chair, CUSB",
    category: "Project & Research",
    categoryKey: "project",
    status: "Open",
    qualifications: "Project Associate: Master's in Social Sciences / Public Policy. MTS: Matriculation with computer proficiency.",
    fellowship: "Project Associate: ₹31,000/- pm. MTS: ₹18,000/- pm consolidated."
  },
  {
    id: 7,
    page: 1,
    title: "Appointment of Vice-Chancellor of Central University of South Bihar",
    publishedDate: "22 May 2026",
    publishedDateIso: "2026-05-22",
    closingDate: "22 June 2026",
    projectCode: "CUSB/VC/2026",
    fundingAgency: "Ministry of Education, Govt. of India",
    postName: "Vice-Chancellor",
    vacancies: 1,
    department: "Executive University Leadership",
    principalInvestigator: "Search-cum-Selection Committee, MoE",
    category: "Executive & Statutory",
    categoryKey: "statutory",
    status: "Closed",
    qualifications: "Distinguished academician with minimum 10 years experience as Professor in a University system or reputed research/academic administrative organization.",
    fellowship: "Apex Level Pay Scale (Level 15) with Special Allowance."
  },
  {
    id: 8,
    page: 1,
    title: "Advertisement for the post of CRS Project Fellow (Junior)-I / CRS Project Fellow (Junior)-II (01-Post) under under UGC-DAE-CSR-funded Project CUSB-RP-124",
    publishedDate: "20 May 2026",
    publishedDateIso: "2026-05-20",
    closingDate: "10 June 2026",
    projectCode: "CUSB-RP-124",
    fundingAgency: "UGC-DAE-CSR",
    postName: "CRS Project Fellow (Junior)-I / II",
    vacancies: 1,
    department: "Department of Physics",
    principalInvestigator: "Principal Investigator, Condensed Matter Physics Lab",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Physics / Materials Science with minimum 55% marks (Fellow-II requires NET/GATE).",
    fellowship: "₹14,000/- pm (Fellow-I) or ₹31,000/- pm (Fellow-II) + HRA."
  },
  {
    id: 9,
    page: 1,
    title: "Advertisement for the post of CRS Project Fellow (Junior)-I / CRS Project Fellow (Junior)-II (01-Post) under under UGC-DAE-CSR-funded Project CUSB-RP-123",
    publishedDate: "14 May 2026",
    publishedDateIso: "2026-05-14",
    closingDate: "04 June 2026",
    projectCode: "CUSB-RP-123",
    fundingAgency: "UGC-DAE-CSR",
    postName: "CRS Project Fellow (Junior)-I / II",
    vacancies: 1,
    department: "Department of Chemistry",
    principalInvestigator: "Principal Investigator, Inorganic Chemistry Division",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Chemistry with first class honors.",
    fellowship: "₹14,000/- pm (Fellow-I) or ₹31,000/- pm (Fellow-II) + HRA."
  },
  {
    id: 10,
    page: 1,
    title: "Advertisement for the post of Research Assistant (01- Post) & Field Investigator (02-Posts) under ICSSR-funded Project CUSB-RP-122",
    publishedDate: "08 May 2026",
    publishedDateIso: "2026-05-08",
    closingDate: "28 May 2026",
    projectCode: "CUSB-RP-122",
    fundingAgency: "ICSSR",
    postName: "Research Assistant & Field Investigator",
    vacancies: 3,
    department: "Department of Economics / Development Studies",
    principalInvestigator: "Project Director, ICSSR Major Research Project",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "RA: Ph.D. / M.Phil / Master's in Social Science with 55%. Field Investigator: Master's with field survey experience.",
    fellowship: "RA: ₹37,000/- pm. Field Investigator: ₹20,000/- pm."
  },

  // ─── PAGE 2 (10 Advertisements) ───
  {
    id: 11,
    page: 2,
    title: "Advertisement for Project Associate-I (01 Position), Project Associate - I (02 Position ) in BSBB Project",
    publishedDate: "30 January 2026",
    publishedDateIso: "2026-01-30",
    closingDate: "20 February 2026",
    projectCode: "BSBB-PROJ-01",
    fundingAgency: "Bihar State Biodiversity Board (BSBB)",
    postName: "Project Associate-I",
    vacancies: 3,
    department: "Department of Botany & Environmental Science",
    principalInvestigator: "Principal Investigator, BSBB Project, CUSB",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Botany / Forestry / Ecology / Biodiversity / Wildlife Sciences with field experience in Bihar biodiversity documentation.",
    fellowship: "₹31,000/- per month + HRA."
  },
  {
    id: 12,
    page: 2,
    title: "Advertisement for Non-Teaching Positions",
    publishedDate: "16 December 2025",
    publishedDateIso: "2025-12-16",
    closingDate: "15 January 2026",
    projectCode: "CUSB/NT/2025/02",
    fundingAgency: "University Main Budget",
    postName: "Non-Teaching Positions (Various Cadres)",
    vacancies: 18,
    department: "University Central Administration",
    principalInvestigator: "Registrar, CUSB",
    category: "Non-Teaching Positions",
    categoryKey: "non-teaching",
    status: "Closed",
    qualifications: "Positions including Section Officer, Assistant, Technical Assistant, Junior Professional Assistant, and Lower Division Clerk.",
    fellowship: "7th CPC Pay Matrix Levels 2 to 8 with standard allowances."
  },
  {
    id: 13,
    page: 2,
    title: "RECRUITMENT OF TEACHING AND NON-TEACHING",
    publishedDate: "15 December 2025",
    publishedDateIso: "2025-12-15",
    closingDate: "20 January 2026",
    projectCode: "CUSB/TNT/2025/01",
    fundingAgency: "University Main Budget / UGC",
    postName: "Special Recruitment Drive (Teaching & Non-Teaching)",
    vacancies: 24,
    department: "Multiple University Departments",
    principalInvestigator: "Recruitment Cell, CUSB",
    category: "Teaching & Faculty",
    categoryKey: "faculty",
    status: "Closed",
    qualifications: "UGC / AICTE / BCI / NCTE minimum standards for faculty; DoPT recruitment rules for statutory & administrative staff.",
    fellowship: "Academic Pay Level 10 to 14 (Teaching) and Pay Level 4 to 12 (Non-Teaching)."
  },
  {
    id: 14,
    page: 2,
    title: "Advertisement for appointment of Project staff under RP-118 (Dated: 02-12-2025)",
    publishedDate: "04 December 2025",
    publishedDateIso: "2025-12-04",
    closingDate: "24 December 2025",
    projectCode: "CUSB-RP-118",
    fundingAgency: "DST",
    postName: "Project Associate-II",
    vacancies: 1,
    department: "Department of Bioinformatics",
    principalInvestigator: "Dr. Nemi Rathore, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. / M.Tech in Bioinformatics / Computational Biology with 2 years research experience.",
    fellowship: "₹35,000/- per month + HRA."
  },
  {
    id: 15,
    page: 2,
    title: "Regarding uploading Advertisement and Application form for project staff under CUSB-RP-117",
    publishedDate: "19 November 2025",
    publishedDateIso: "2025-11-19",
    closingDate: "10 December 2025",
    projectCode: "CUSB-RP-117",
    fundingAgency: "DBT",
    postName: "Project JRF / Project Fellow",
    vacancies: 1,
    department: "Department of Biotechnology",
    principalInvestigator: "Dr. Rakesh Kumar, Associate Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Biotechnology / Life Sciences / Molecular Biology with valid national test score.",
    fellowship: "₹31,000/- per month + HRA."
  },
  {
    id: 16,
    page: 2,
    title: "Advertisement for appointment of project staff under DST-PURSE project sanctioned to CUSB",
    publishedDate: "25 September 2025",
    publishedDateIso: "2025-09-25",
    closingDate: "15 October 2025",
    projectCode: "DST-PURSE-01",
    fundingAgency: "DST-PURSE",
    postName: "Project Scientists, Associates & Technical Assistants",
    vacancies: 8,
    department: "Central Instrumentation Facility (CIF), CUSB",
    principalInvestigator: "DST-PURSE Project Coordinator, CUSB",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "Ph.D. / M.Tech / M.Sc. in Instrumentation, Material Science, Chemistry, Physics, or Biotechnology.",
    fellowship: "Project Scientist: ₹56,000/- pm. Associate: ₹31,000/- pm. Tech Assistant: ₹20,000/- pm."
  },
  {
    id: 17,
    page: 2,
    title: "Advertisement for Walk-in Interview for Junior Research Felloe (JRF-One) in the Departmental of Environmental Science",
    publishedDate: "12 August 2025",
    publishedDateIso: "2025-08-12",
    closingDate: "25 August 2025",
    projectCode: "CUSB-ENV-09",
    fundingAgency: "ISRO / RESPOND",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Environmental Science",
    principalInvestigator: "Prof. Ram Kumar, Professor & Head",
    category: "Walk-in Interviews",
    categoryKey: "walkin",
    status: "Closed",
    qualifications: "Postgraduate degree in Environmental Science / Remote Sensing with GIS proficiency.",
    fellowship: "₹31,000/- per month + HRA."
  },
  {
    id: 18,
    page: 2,
    title: "Advertisement for Walking Interview for Junior Research Fellow (JRF)",
    publishedDate: "11 August 2025",
    publishedDateIso: "2025-08-11",
    closingDate: "22 August 2025",
    projectCode: "CUSB-CHEM-04",
    fundingAgency: "CSIR",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Chemistry",
    principalInvestigator: "Dr. Girish Chandra, Assistant Professor",
    category: "Walk-in Interviews",
    categoryKey: "walkin",
    status: "Closed",
    qualifications: "M.Sc. in Organic / Inorganic Chemistry with NET / GATE.",
    fellowship: "₹31,000/- per month + HRA."
  },
  {
    id: 19,
    page: 2,
    title: "Advertisement for the post of Project Assistant under SERB-funded Project CUSB-RP-87",
    publishedDate: "20 June 2025",
    publishedDateIso: "2025-06-20",
    closingDate: "10 July 2025",
    projectCode: "CUSB-RP-87",
    fundingAgency: "SERB",
    postName: "Project Assistant",
    vacancies: 1,
    department: "Department of Mathematics",
    principalInvestigator: "Dr. Vivek Kumar Jain, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "B.Sc. / M.Sc. in Mathematics / Applied Mathematics / Statistics with 55% marks.",
    fellowship: "₹20,000/- per month + HRA as per SERB rules."
  },
  {
    id: 20,
    page: 2,
    title: "Advertisement for the posts of Research Associate, Research Assistant & Field Investigator under ICSSR-funded Project CUSB-RP-115",
    publishedDate: "20 June 2025",
    publishedDateIso: "2025-06-20",
    closingDate: "10 July 2025",
    projectCode: "CUSB-RP-115",
    fundingAgency: "ICSSR",
    postName: "Research Associate, Assistant & Field Investigator",
    vacancies: 3,
    department: "Department of Sociology & Social Work",
    principalInvestigator: "Project Director, ICSSR Special Project",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "RA: Post-graduate in Social Sciences with 55% and NET / M.Phil / Ph.D. Field Investigator: Master's degree in Sociology.",
    fellowship: "RA: ₹47,000/- pm. Assistant: ₹32,000/- pm. Field Investigator: ₹20,000/- pm."
  },

  // ─── PAGE 3 (10 Advertisements) ───
  {
    id: 21,
    page: 3,
    title: "Advertisement for the posts of Research Associate, Research Assistant & Field Investigator under ICSSR-funded Project CUSB-RP-114",
    publishedDate: "20 June 2025",
    publishedDateIso: "2025-06-20",
    closingDate: "10 July 2025",
    projectCode: "CUSB-RP-114",
    fundingAgency: "ICSSR",
    postName: "Research Associate, Research Assistant & Field Investigator",
    vacancies: 3,
    department: "Department of Media & Mass Communication",
    principalInvestigator: "Project Director, Department of Mass Communication",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "Master's degree in Journalism / Mass Communication / Media Studies with research aptitude.",
    fellowship: "RA: ₹47,000/- pm. Research Assistant: ₹32,000/- pm. Field Investigator: ₹20,000/- pm."
  },
  {
    id: 22,
    page: 3,
    title: "Advertisement for the posts of Research Consultant (01-Post) & Web- GIS Developer (01- Post) under CDRI-funded project CUSB-RP-107",
    publishedDate: "30 May 2025",
    publishedDateIso: "2025-05-30",
    closingDate: "20 June 2025",
    projectCode: "CUSB-RP-107",
    fundingAgency: "CDRI",
    postName: "Research Consultant & Web-GIS Developer",
    vacancies: 2,
    department: "Department of Geography & Geoinformatics",
    principalInvestigator: "Principal Investigator, CDRI Disaster Resilience Project",
    category: "Technology & Consulting",
    categoryKey: "tech",
    status: "Closed",
    qualifications: "Consultant: Ph.D. / M.Tech in Remote Sensing / GIS / Disaster Management. Web-GIS Developer: B.Tech / MCA with GeoServer, OpenLayers, Leaflet.",
    fellowship: "Research Consultant: ₹60,000/- pm consolidated. Web-GIS Developer: ₹45,000/- pm."
  },
  {
    id: 23,
    page: 3,
    title: "Advertisement for the posts of Project Associate-I (02-Posts), Project Associate - II (02-Posts) & Lab Assistant under PURSE-funded project CUSB-RP-111",
    publishedDate: "29 April 2025",
    publishedDateIso: "2025-04-29",
    closingDate: "20 May 2025",
    projectCode: "CUSB-RP-111",
    fundingAgency: "DST-PURSE",
    postName: "Project Associate-I, II & Lab Assistant",
    vacancies: 5,
    department: "School of Physical and Chemical Sciences",
    principalInvestigator: "Coordinator, DST-PURSE Project, CUSB",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "PA-I: M.Sc. in Physics/Chemistry. PA-II: M.Sc. with 2 yrs exp. Lab Assistant: B.Sc. in Science.",
    fellowship: "PA-I: ₹31,000/- pm. PA-II: ₹35,000/- pm. Lab Assistant: ₹20,000/- pm + HRA."
  },
  {
    id: 24,
    page: 3,
    title: "Advertisement for the post of Project Research Scientist - I (Non-Medical) under the ICMR-sponsored Research Project CUSB-RP-112",
    publishedDate: "28 March 2025",
    publishedDateIso: "2025-03-28",
    closingDate: "18 April 2025",
    projectCode: "CUSB-RP-112",
    fundingAgency: "ICMR",
    postName: "Project Research Scientist - I (Non-Medical)",
    vacancies: 1,
    department: "Department of Pharmacy",
    principalInvestigator: "Dr. Prashant Kumar, Associate Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "First class Master's degree in Pharmacology / Biotechnology / Life Sciences with 3 years experience or Ph.D.",
    fellowship: "₹56,000/- per month + HRA (18%)."
  },
  {
    id: 25,
    page: 3,
    title: "Advertisement for Faculty Positions",
    publishedDate: "25 October 2024",
    publishedDateIso: "2024-10-25",
    closingDate: "25 November 2024",
    projectCode: "CUSB/Advt./37/2024",
    fundingAgency: "University Main Budget / UGC",
    postName: "Professor, Associate Professor & Assistant Professor",
    vacancies: 32,
    department: "All University Schools & Departments",
    principalInvestigator: "Recruitment Cell, CUSB",
    category: "Teaching & Faculty",
    categoryKey: "faculty",
    status: "Closed",
    qualifications: "As per UGC Regulations on Minimum Qualifications for Appointment of Teachers 2018 and subsequent amendments.",
    fellowship: "7th CPC Academic Pay Level 14 (Professor), Level 13A (Associate Professor), Level 10 (Assistant Professor)."
  },
  {
    id: 26,
    page: 3,
    title: "Advertisement for Non-Teaching Positions",
    publishedDate: "19 October 2024",
    publishedDateIso: "2024-10-19",
    closingDate: "18 November 2024",
    projectCode: "CUSB/Advt./36/2024",
    fundingAgency: "University Main Budget",
    postName: "Various Group 'A', 'B' & 'C' Non-Teaching Posts",
    vacancies: 15,
    department: "Administrative & Technical Cadre",
    principalInvestigator: "Registrar, CUSB",
    category: "Non-Teaching Positions",
    categoryKey: "non-teaching",
    status: "Closed",
    qualifications: "Degrees / Diplomas in relevant engineering, administrative, library science, or secretarial domains as detailed in vacancy bulletin.",
    fellowship: "7th CPC Pay Scale Matrix Levels 2 through 10."
  },
  {
    id: 27,
    page: 3,
    title: "Advertisement for the post of JRF/ Project Fellow under the IUAC-UFR-sponsored Research Project CUSB-RP-108",
    publishedDate: "17 October 2024",
    publishedDateIso: "2024-10-17",
    closingDate: "07 November 2024",
    projectCode: "CUSB-RP-108",
    fundingAgency: "IUAC-UFR",
    postName: "JRF / Project Fellow",
    vacancies: 1,
    department: "Department of Physics",
    principalInvestigator: "Dr. Rohit R. Shahi, Associate Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Physics with minimum 55% marks. Candidates with NET/GATE preferred.",
    fellowship: "₹31,000/- pm (JRF) or ₹14,000/- pm (Project Fellow) + HRA."
  },
  {
    id: 28,
    page: 3,
    title: "SRF position for CCRUM funded project",
    publishedDate: "09 October 2024",
    publishedDateIso: "2024-10-09",
    closingDate: "30 October 2024",
    projectCode: "CCRUM-RP-04",
    fundingAgency: "CCRUM (Ministry of AYUSH)",
    postName: "Senior Research Fellow (SRF)",
    vacancies: 1,
    department: "Department of Pharmacy",
    principalInvestigator: "Dr. Vivek Dave, Associate Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Pharm in Pharmacognosy / Pharmaceutical Chemistry with 2 years research experience.",
    fellowship: "₹35,000/- per month + HRA."
  },
  {
    id: 29,
    page: 3,
    title: "Advertisement for Medical Officer(Female) on contract basis",
    publishedDate: "04 October 2024",
    publishedDateIso: "2024-10-04",
    closingDate: "24 October 2024",
    projectCode: "CUSB/MED/2024/01",
    fundingAgency: "University Health Budget",
    postName: "Medical Officer (Female) — Contractual",
    vacancies: 1,
    department: "University Health Centre, CUSB",
    principalInvestigator: "Chief Medical Officer / Registrar, CUSB",
    category: "Medical & Healthcare",
    categoryKey: "medical",
    status: "Closed",
    qualifications: "MBBS recognized by the National Medical Commission (NMC) with 2 years clinical experience in a recognized hospital.",
    fellowship: "Consolidated monthly remuneration of ₹75,000/- per month."
  },
  {
    id: 30,
    page: 3,
    title: "Advertisement for the post of Research Assistant (01- Post) & Field Assistant (01-Post) under the CDRI-sponsored Research Project CUSB-RP-107",
    publishedDate: "18 September 2024",
    publishedDateIso: "2024-09-18",
    closingDate: "08 October 2024",
    projectCode: "CUSB-RP-107",
    fundingAgency: "CDRI",
    postName: "Research Assistant & Field Assistant",
    vacancies: 2,
    department: "Department of Environmental Science & Geoinformatics",
    principalInvestigator: "Principal Investigator, CDRI Collaborative Study",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "RA: Master's in Environmental Science / Disaster Management. Field Assistant: Graduate with surveying experience.",
    fellowship: "RA: ₹31,000/- pm. Field Assistant: ₹18,000/- pm consolidated."
  },

  // ─── PAGE 4 (8 Historical Advertisements completing the 4-page pagination) ───
  {
    id: 31,
    page: 4,
    title: "Advertisement for the post of Junior Research Fellow (JRF) under DST-SERB Project CUSB-RP-105",
    publishedDate: "02 September 2024",
    publishedDateIso: "2024-09-02",
    closingDate: "22 September 2024",
    projectCode: "CUSB-RP-105",
    fundingAgency: "DST-SERB",
    postName: "Junior Research Fellow (JRF)",
    vacancies: 1,
    department: "Department of Physics",
    principalInvestigator: "Dr. Budhendra Singh, Assistant Professor",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "M.Sc. in Physics with minimum 55% marks and valid GATE / CSIR-NET.",
    fellowship: "₹31,000/- per month + HRA."
  },
  {
    id: 32,
    page: 4,
    title: "Advertisement for Guest Faculty in Department of Mathematics & Statistics",
    publishedDate: "22 August 2024",
    publishedDateIso: "2024-08-22",
    closingDate: "10 September 2024",
    projectCode: "CUSB/GF/2024/03",
    fundingAgency: "University Academic Fund",
    postName: "Guest Faculty (Mathematics & Statistics)",
    vacancies: 4,
    department: "Department of Mathematics & Statistics",
    principalInvestigator: "Head of the Department",
    category: "Teaching & Faculty",
    categoryKey: "faculty",
    status: "Closed",
    qualifications: "Master's degree with 55% marks and NET / Ph.D. in Mathematics or Statistics.",
    fellowship: "Honorarium of ₹1,500/- per lecture subject to a maximum of ₹50,000/- per month."
  },
  {
    id: 33,
    page: 4,
    title: "Walk-in Interview for Assistant Professor (Contractual) in School of Law & Governance",
    publishedDate: "10 August 2024",
    publishedDateIso: "2024-08-10",
    closingDate: "24 August 2024",
    projectCode: "CUSB/LAW/2024/02",
    fundingAgency: "University Main Budget",
    postName: "Assistant Professor (Contractual)",
    vacancies: 3,
    department: "School of Law & Governance",
    principalInvestigator: "Dean, School of Law & Governance",
    category: "Walk-in Interviews",
    categoryKey: "walkin",
    status: "Closed",
    qualifications: "LL.M. with minimum 55% marks and UGC-NET / Ph.D. in Law.",
    fellowship: "Consolidated salary of ₹57,700/- per month."
  },
  {
    id: 34,
    page: 4,
    title: "Advertisement for Consultant (Internal Audit & Finance) on Contractual Basis",
    publishedDate: "25 July 2024",
    publishedDateIso: "2024-07-25",
    closingDate: "15 August 2024",
    projectCode: "CUSB/FIN/2024/01",
    fundingAgency: "University Administrative Fund",
    postName: "Consultant (Internal Audit & Finance)",
    vacancies: 1,
    department: "Finance & Accounts Department",
    principalInvestigator: "Finance Officer, CUSB",
    category: "Non-Teaching Positions",
    categoryKey: "non-teaching",
    status: "Closed",
    qualifications: "Retired Audit / Accounts Officer from Central Government, CAG, or Central Autonomous Bodies.",
    fellowship: "As per Ministry of Finance rules (Last pay drawn minus pension + conveyance)."
  },
  {
    id: 35,
    page: 4,
    title: "Rolling Advertisement for Teaching Positions (Professor, Associate Professor, Assistant Professor) Advt. No. CUSB/Advt./35/2024",
    publishedDate: "15 July 2024",
    publishedDateIso: "2024-07-15",
    closingDate: "14 August 2024",
    projectCode: "CUSB/Advt./35/2024",
    fundingAgency: "UGC / MoE",
    postName: "Rolling Faculty Recruitment (Various Disciplines)",
    vacancies: 45,
    department: "All Academic Schools of CUSB",
    principalInvestigator: "Recruitment Cell, CUSB",
    category: "Teaching & Faculty",
    categoryKey: "faculty",
    status: "Closed",
    qualifications: "As per UGC Regulations 2018 and AICTE/NCTE norms.",
    fellowship: "Academic Level 10 to Level 14 with all central government allowances."
  },
  {
    id: 36,
    page: 4,
    title: "Advertisement for Technical Assistant and Lab Attendant in School of Physical Sciences",
    publishedDate: "28 June 2024",
    publishedDateIso: "2024-06-28",
    closingDate: "18 July 2024",
    projectCode: "CUSB/TECH/2024/01",
    fundingAgency: "University Technical Cadre",
    postName: "Technical Assistant & Lab Attendant",
    vacancies: 4,
    department: "School of Physical Sciences",
    principalInvestigator: "Dean, School of Physical Sciences",
    category: "Non-Teaching Positions",
    categoryKey: "non-teaching",
    status: "Closed",
    qualifications: "Tech Assistant: B.Sc. with 2 yrs laboratory experience. Lab Attendant: 10+2 with Science stream.",
    fellowship: "Pay Level 5 (Tech Assistant) & Pay Level 1 (Lab Attendant)."
  },
  {
    id: 37,
    page: 4,
    title: "Advertisement for Post-Doctoral Fellow (PDF) under Institute of Eminence Research Grant",
    publishedDate: "14 June 2024",
    publishedDateIso: "2024-06-14",
    closingDate: "05 July 2024",
    projectCode: "CUSB-PDF-2024",
    fundingAgency: "UGC / Institute Research Fund",
    postName: "Post-Doctoral Fellow (PDF)",
    vacancies: 2,
    department: "Department of Life Science & Biotechnology",
    principalInvestigator: "Dean, Research & Development, CUSB",
    category: "Project & Research",
    categoryKey: "project",
    status: "Closed",
    qualifications: "Ph.D. in Biological Sciences / Biotechnology / Molecular Biology with high-impact SCI publications.",
    fellowship: "₹54,000/- per month + HRA and annual contingency grant of ₹1,00,000/-."
  },
  {
    id: 38,
    page: 4,
    title: "Recruitment of Chief Medical Officer (CMO) and Senior Medical Staff",
    publishedDate: "30 May 2024",
    publishedDateIso: "2024-05-30",
    closingDate: "20 June 2024",
    projectCode: "CUSB/CMO/2024",
    fundingAgency: "University Health Cadre",
    postName: "Chief Medical Officer (CMO)",
    vacancies: 1,
    department: "University Health Centre",
    principalInvestigator: "Registrar, CUSB",
    category: "Medical & Healthcare",
    categoryKey: "medical",
    status: "Closed",
    qualifications: "MD / MS in Medicine / General Surgery with minimum 10 years clinical experience in government/reputed hospitals.",
    fellowship: "Pay Level 12 (7th CPC) with Non-Practicing Allowance (NPA)."
  }
];
